import Head from "next/head";
import FooterC from "../footerC";
import NavbarC from "../navbarC";
export default function Layout({ children, title }) {
  return (
    <>
      <Head>
        <title>{title ?? ""}Pasisia Developers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <NavbarC />
      <main>{children}</main>
      <FooterC />
    </>
  );
}
